In [1]:
a = int(5)
b = int(3)
c = a + b
print(c)

8


In [7]:
print(np.__version__)

1.26.4


In [9]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3])
result = np.append(arr, [4, 5, 6])
print(arr)
print("Array after append : ", result)

[1 2 3]
Array after append :  [1 2 3 4 5 6]


In [15]:
arr1 = np.array([1.123456, 2.789101, 0.0000001])
print(np.array2string(arr1))

[1.123456e+00 2.789101e+00 1.000000e-07]


In [16]:
arr1 = np.array([13, 14, 3])
arr2 = np.array([17, 13, 13])

result = np.bitwise_and(arr1, arr2)
print(result)

[ 1 12  1]


In [18]:
pos_inf = np.inf
neg_inf = -np.inf
arr = np.array([1.0, np.inf, -np.inf, 4.5])
print(np.isinf(arr))    
print(np.isposinf(arr))    
print(np.isfinite(arr))

[False  True  True False]
[False  True False False]
[ True False False  True]


In [20]:
import pandas as pd

In [21]:
pip show pandas

Name: pandas
Version: 2.2.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be u

In [22]:
data = np.array(['g', 'e', 'e', 'k', 's'])
s = pd.Series(data)
print("Pandas Series:")
print(s)

Pandas Series:
0    g
1    e
2    e
3    k
4    s
dtype: object


In [24]:
df = pd.DataFrame() 
print(df)
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'] 
  
df = pd.DataFrame(lst) 
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks
